"""initial schema

Revision ID: ed054bd95378
Revises: 
Create Date: 2026-08-30 23:16:59.970732

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed054bd95378'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('processed_webhook_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('researcher', 'transcriptionist', 'platform_admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('historical_archives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_type', sa.Enum('user', 'archive', 'platform', name='ledgeraccountownertype'), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('owner_archive_id', sa.String(), nullable=True),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'closed', name='ledgeraccountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(owner_type = 'user' AND owner_user_id IS NOT NULL AND owner_archive_id IS NULL) OR (owner_type = 'archive' AND owner_archive_id IS NOT NULL AND owner_user_id IS NULL) OR (owner_type = 'platform' AND owner_user_id IS NULL AND owner_archive_id IS NULL)", name='ck_ledger_account_owner_matches_type'),
    sa.ForeignKeyConstraint(['owner_archive_id'], ['historical_archives.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_archive_id'),
    sa.UniqueConstraint('owner_user_id')
    )
    op.create_table('research_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('archive_id', sa.String(), nullable=False),
    sa.Column('record_reference', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('transcriptionist_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['historical_archives.id'], ),
    sa.ForeignKeyConstraint(['transcriptionist_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_records_record_reference'), 'research_records', ['record_reference'], unique=True)
    op.create_table('authorizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=False),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'authorized', 'declined', 'expired', name='authorizationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_record_id'], ['research_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizations_external_reference'), 'authorizations', ['external_reference'], unique=True)
    op.create_index(op.f('ix_authorizations_research_record_id'), 'authorizations', ['research_record_id'], unique=False)
    op.create_index(op.f('ix_authorizations_user_id'), 'authorizations', ['user_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('authorization_id', sa.String(), nullable=False),
    sa.Column('settled_amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('settled', 'failed', 'reversed', name='settlementstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ledger_account_id', sa.String(), nullable=False),
    sa.Column('settlement_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('debit', 'credit', name='transactiontype'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'posted', 'reversed', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_ledger_account_id'), 'transactions', ['ledger_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_settlement_id'), 'transactions', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_settlement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ledger_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_authorizations_user_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_research_record_id'), table_name='authorizations')
    op.drop_index(op.f('ix_authorizations_external_reference'), table_name='authorizations')
    op.drop_table('authorizations')
    op.drop_index(op.f('ix_research_records_record_reference'), table_name='research_records')
    op.drop_table('research_records')
    op.drop_table('ledger_accounts')
    op.drop_table('historical_archives')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('processed_webhook_events')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
